In [1]:
import pandas as pd
from src.data.metrics import get_metrics
import numpy as np

In [ ]:
# Get best hyperparameters for TUL methods
df = pd.read_json("../reports/method_hparams_TUL.jsonl", lines=True)
metrics = ["top_1_accuracy"]
get_metrics(df, metrics)
hparams = [
    "loc_levels",
    "discretization_rows",
    "grow_factor",
    "embedding_type",
    "replay_buffer_type",
    "embedding_weight_factor",
    "replay_batch_size",
    "lr",
    "optimizer_cls"
]
idcs_max = df.groupby(["embedding_type", "replay_buffer_type", "optimizer_cls"])[
    "top_1_accuracy"
].idxmax()
df.loc[idcs_max][hparams + metrics]

,loc_levels,discretization_rows,grow_factor,embedding_type,replay_buffer_type,embedding_weight_factor,replay_batch_size,lr,optimizer_cls,top_1_accuracy
159,1,100,2,lookup_concat,balanced,2,2.0,0.0002,Adam,0.5754
100,1,100,2,lookup_concat,none,2,16.0,0.0002,AdamHD,0.5778
112,1,100,2,lookup_concat,none,2,16.0,0.0008,UPGD,0.0306
48,4,200,2,lookup_weighted_concat,none,2,none,0.0002,Adam,0.5930
95,1,100,2,sinusoidal,none,4000,16.0,0.0002,Adam,0.5606

In [36]:
df = pd.read_json("../reports/method_hparams_DP.jsonl", lines=True)
df["mean_dist"] = df["pred_dists"].apply(lambda x: np.mean(x))

hparams = [
    "loc_levels",
    "discretization_rows",
    "grow_factor",
    "embedding_type",
    "replay_buffer_type",
    "embedding_weight_factor",
    "replay_batch_size",
    'lr'
]

min_idcs = df.groupby(["embedding_type", "replay_buffer_type"])["mean_dist"].idxmin()
df.loc[min_idcs][hparams + ["mean_dist"]]

,loc_levels,discretization_rows,grow_factor,embedding_type,replay_buffer_type,embedding_weight_factor,replay_batch_size,lr,mean_dist
39,1,100,2,fourier,none,2000,16,0.0001,4423.946222
43,1,100,2,lookup_concat,random,2,4,0.0001,3943.924722
30,5,200,4,lookup_weighted_concat,none,2,16,0.0001,4296.603382

In [63]:
df = pd.read_json("../reports/method_hparams_batch.jsonl", lines=True)
# df["mean_dist"] = df["pred_dists"].apply(lambda x: np.mean(x))

hparams = [
    "loc_levels",
    "discretization_rows",
    "grow_factor",
    "embedding_weight_factor",
]

min_idcs = df.groupby(["embedding_type"])["top_1_accuracy"].idxmax()
df.loc[min_idcs][hparams + ["top_1_accuracy"]]

,loc_levels,discretization_rows,grow_factor,embedding_weight_factor,top_1_accuracy
83,5,400,4,2,0.754

In [61]:
df[hparams + ["top_1_accuracy"]].sort_values(by='top_1_accuracy')

,loc_levels,discretization_rows,grow_factor,embedding_weight_factor,top_1_accuracy
76,5,300,4,1,0.722
24,3,500,2,1,0.723
48,4,400,2,1,0.723
57,4,500,3,2,0.724
25,3,500,2,2,0.725
...,...,...,...,...,...
8,3,200,3,1,0.749
71,5,200,4,2,0.749
41,4,200,4,2,0.751
82,5,400,4,1,0.751
83,5,400,4,2,0.754