In [2]:
import pandas as pd
import numpy as np
from src.data.metrics import get_metrics

In [ ]:
hparams = [
    "model_cls",
    "lr",
    "n_hidden",
    "n_layers",
    "time_embedding_factor",
    "dropout",
    "n_heads",
    "lambduh",
]
metrics = [
    "top_1_accuracy",
]
df = pd.read_json("../reports/model_hparams_TUL.jsonl", lines=True)
get_metrics(df, metrics)
max_idcs = df.groupby("model_cls")['top_1_accuracy'].idxmax()
df.loc[max_idcs][hparams+metrics]

,model_cls,lr,n_hidden,n_layers,time_embedding_factor,dropout,n_heads,lambduh,top_1_accuracy
412,BiTULER,0.0002,1024,1,0.0625,0,NaN,NaN,0.5674
550,DeepTUL,0.0004,1024,2,0.0625,0,NaN,NaN,0.5372
300,MainTUL,0.0002,1024,1,0.0625,0,8.0,2.0,0.4642
193,T3S,0.0001,1024,1,0.0625,0,16.0,NaN,0.4258
62,TULHOR,0.0001,1024,1,0.0625,0,16.0,NaN,0.4714
461,TULVAE,0.0002,1024,1,0.0625,0,NaN,NaN,0.5210

In [ ]:
hparams = [
    "model_cls",
    "lr",
    "n_hidden",
    "n_heads",
    "n_layers",
    "embedding_type",
    "n_filters"
]
df = pd.read_json("../reports/model_hparams_DP.jsonl", lines=True)
df['mean_dist'] = df['pred_dists'].apply(np.mean)
min_idcs = df.groupby("model_cls")['mean_dist'].idxmin()
df.loc[min_idcs][hparams + ['mean_dist']]

,model_cls,lr,n_hidden,n_heads,n_layers,embedding_type,n_filters,mean_dist
9,BiLSTM,0.0001,1024,NaN,2,lookup_concat,NaN,4650.021611
47,CNN,0.0001,1024,NaN,2,lookup_concat,256.0,5238.089476
117,MLP,0.0002,1024,NaN,3,lookup_concat,NaN,5836.429779
33,Transformer,0.0001,1024,16.0,1,lookup_concat,NaN,7242.758245

In [8]:
hparams = [
    "model_cls",
    "lr",
    "n_hidden",
    "n_layers",
]
metrics = [
    "top_1_accuracy",
]
df = pd.read_json("../reports/model_hparams_batch.jsonl", lines=True)
max_idcs = df.groupby("model_cls")['top_1_accuracy'].idxmax()
df.loc[max_idcs][hparams+metrics]

  model_cls      lr  n_hidden  n_layers  top_1_accuracy
0   BiTULER  0.0001      1024         1           0.728